services:
  - type: worker
    name: zafrobot-scalper-pro-v1
    env: python
    plan: starter
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: API_PASSPHRASE
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false